Data.Map used instead of pairs in Generator.hs
Lev135/latex-generator pull request #22
Opened 2022-03-20 14:18 UTC by Cianidos

Definition refactored with Map instead of pairs. Code adopted to this. No features of Map not used yet.

2022-03-20 14:55 UTC, Lev135 commented on src/Generator.hs
> +    where
На мой взгляд часть этих определений избыточны, `uncurry T.replace` гораздо понятнее, чем pairReplace. Предлагаю сделать так:
```
fs = map (uncurry T.replace . second showCmd) (M.toList mathCmds)
showCmd = (<> " ") . val
```

2022-03-20 14:59 UTC, Lev135 requested changes
Всё-таки вместе с этими изменениями, наверное, логично сразу добавить проверку на повторное объявление переменных. Для этого processDefs должен возвращать Either, а в его вызове нужно воспользоваться Utils.eitherFail

2022-03-20 15:03 UTC, Cianidos commented on src/Generator.hs
> +    where
Я просто забыл удалить их. Сделал, чтобы понять, что вообще делает эта функция. Я изначально хотел переделать её так, чтобы шла обработка самой Map (без toList), но не придумал(

2022-03-20 15:04 UTC, Lev135 commented
Да, ещё лучше использовать `Data.Map.Strict as M` вроде бы

2022-03-20 15:10 UTC, Lev135 commented
Вот эта функция (написана мной) может помочь, вроде бы. Ну или просто проверить на пересечение перед объединением. Но так, вроде бы, красивее. 
```
import qualified Data.Map.Merge.Strict as M

-- | unite Maps with side effects
unionWithA :: (Ord k, Applicative m) => (a -> a -> m a) -> M.Map k a -> M.Map k a -> m (M.Map k a)
unionWithA g = M.mergeA hMiss hMiss hMatched
    where
        hMiss       = M.mapMissing $ const id
        hMatched    = M.zipWithAMatched $ const g
```

2022-03-20 15:15 UTC, Lev135 commented on src/Generator.hs
> +    where
> Я просто забыл удалить их. Сделал, чтобы понять, что вообще делает эта функция. Я изначально хотел переделать её так, чтобы шла обработка самой Map (без toList), но не придумал(

Вроде бы, если map заменить на fmap должно и внутри `Map` работать, так как она и `Functor` и `Foldable`

2022-03-20 15:53 UTC, Lev135 commented
В `unionWithA` лучше заменить `mapMissing` на [`preserveMissing`](https://hackage.haskell.org/package/containers-0.6.5.1/docs/Data-Map-Internal.html#v:preserveMissing)

2022-03-20 18:13 UTC, Lev135 requested changes

2022-03-20 18:13 UTC, Lev135 commented on src/Utils.hs
> +        hMiss       = M.mapMissing $ const id
Вот тут мой предыдущий комментарий. Лучше сделать `preserveMissing`

2022-04-01 13:18 UTC, Lev135 requested changes

2022-04-01 13:18 UTC, Lev135 commented on src/Generator.hs
> +    where
Да, тут ещё есть проблема с заменой более коротких и длинных строк. Чтобы всё работало правильно длинные строки должны проходить замену раньше коротких. 
Но я нашёл лучшее решение. Есть готовый пакет Text.Replace и в нём функция [replaceWithMap](https://hackage.haskell.org/package/text-replace-0.1.0.2/docs/Text-Replace.html#v:replaceWithMap). И как сказано в документации, наверное, в нашем случае лучше использовать [mapToTrie](https://hackage.haskell.org/package/text-replace-0.1.0.2/docs/Text-Replace.html#v:mapToTrie) и [replaceWithTrie](https://hackage.haskell.org/package/text-replace-0.1.0.2/docs/Text-Replace.html#v:replaceWithTrie). 

Там есть свои сложности с NonEmptyText в ключе, но думаю разобраться с ними будет не так сложно, а работать станет намного эффективнее и корректнее, чем сейчас (проблема перекрывающихся подстрок прям актуальная)

2022-04-02 16:33 UTC, Lev135 commented
Я провёл кардинальные преобразования вывода сделав его через Pretty-print. Думаю, будет проще переписать этот PR заново уже со свежей веткой master

2022-04-03 05:20 UTC, closed without merging